version: '1.0'

services:
  database:
    env_file: ./.env
    image: postgres:13
    container_name: postgres-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
